"""add knowledge_level to agents

Revision ID: 9dd44b55cb91
Revises: b91bdfb37923
Create Date: 2026-03-13 02:36:21.305504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dd44b55cb91'
down_revision: Union[str, Sequence[str], None] = 'b91bdfb37923'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('knowledge_level', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'knowledge_level')
    # ### end Alembic commands ###
